/**
 * Lesson Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudentDto } from './studentDto';


export class FamilyDto { 
    id?: any;
    name?: string | null;
    members?: Array<StudentDto> | null;
    ekleyenKullaniciId?: any | null;
    guncelleyenKullaniciId?: any | null;
    
    eklemeTarihi?:any;
}

