/**
 * Lesson Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Student } from './student';


export class Family { 
    id?: string;
    aktifMi?: boolean | null;
    eklemeTarihi?: string | null;
    ekleyenKullaniciId?: string | null;
    guncellemeTarihi?: string | null;
    guncelleyenKullaniciId?: string | null;
    name?: string | null;
    members?: Array<Student> | null;
}

