/**
 * Lesson Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
//import { Session } from './session';
import { SessionDto } from './sessionDto';


export class Lesson { 
    id?: string;
    aktifMi?: boolean | null;
    eklemeTarihi?: string | null;
    ekleyenKullaniciId?: string | null;
    guncellemeTarihi?: string | null;
    guncelleyenKullaniciId?: string | null;
    name?: string | null;
    sessions?: Array<SessionDto> | null;
}

