/**
 * Lesson Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class RegisterDto { 
    username?: string | null;
    email?: string | null;
    password?: string | null;
    roleName?: string | null;
}

