/**
 * Lesson Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class SessionDto { 
    id?: any;
    studentId?: any;
    teacherId?: any;
    lessonId?: any;
    date?: string;
    durationInHours?: number;
    hourlyPrice?: number;
}

