/**
 * Lesson Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Teacher } from './teacher';
import { Student } from './student';
import { Lesson } from './lesson';


export class Session { 
    id?: string;
    aktifMi?: boolean | null;
    eklemeTarihi?: string | null;
    ekleyenKullaniciId?: string | null;
    guncellemeTarihi?: string | null;
    guncelleyenKullaniciId?: string | null;
    studentId?: string;
    student?: Student;
    teacherId?: string;
    teacher?: Teacher;
    lessonId?: string;
    lesson?: Lesson;
    date?: string;
    durationInHours?: number;
    hourlyPrice?: number;
}

