/**
 * Lesson Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
//import { Family } from './family';
import { FamilyDto } from './familyDto';
//import { Session } from './session';
import { SessionDto } from './sessionDto';


export class StudentDto { 
    id?: any;
    name?: string | null;
    familyId?: string;
    family?: FamilyDto;
    sessions?: Array<SessionDto> | null;
}

