/**
 * Lesson Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class UpdateLessonDto { 
    id?: any;
    name?: string;
    guncelleyenKullaniciId?: any | null;
    ekleyenKullaniciId?: any | null;
    eklemeTarihi?:any;
}

